sylius_twig_hooks:
    hooks:
      'threebrs_contact_form_shop_message_index_breadcrumbs':
          message_index_breadcrumbs_hookable:
              template: '@ThreeBRSSyliusContactFormPlugin/Shop/Account/MessageIndex/breadcrumbs.html.twig'
              priority: 100   

      'threebrs_contact_form_shop_message_index_content':
          message_index_content_hookable:
              template: '@ThreeBRSSyliusContactFormPlugin/Shop/Account/MessageIndex/content.html.twig'
              priority: 100 
          message_index_grid:
              template: '@ThreeBRSSyliusContactFormPlugin/Shop/Account/Grid/message_index_grid.html.twig'
              priority: 50        

      'threebrs_contact_form_shop_message_show_breadcrumbs':
          message_show_breadcrumbs_hookable:
              template: '@ThreeBRSSyliusContactFormPlugin/Shop/Account/MessageShow/breadcrumbs.html.twig'
              priority: 100        

      'threebrs_contact_form_shop_account_menu':
          menu_hookable:
              template: '@ThreeBRSSyliusContactFormPlugin/Shop/Account/MessageShow/menu_override.html.twig'
              priority: 100
      'threebrs_contact_form_shop_message_show_content':
          message_show_content_hookable:
              template: '@ThreeBRSSyliusContactFormPlugin/Shop/Account/MessageShow/content.html.twig'
              priority: 0