threebrs_sylius_contact_form_shop_account_message_index:
  path: messages
  methods: [GET]
  defaults:
    _controller: sylius.controller.shop_user::indexAction
    _sylius:
      section: shop_account
      template: '@ThreeBRSSyliusContactFormPlugin/Shop/Account/index.html.twig'
      grid: threebrs_sylius_account_contact_message

threebrs_sylius_contact_form_shop_account_message_show:
  path: messages/{id}
  methods: [POST, GET]
  defaults:
    _controller: ThreeBRS\SyliusContactFormPlugin\Controller\ContactFormAccountController::showAccountMessageAction
