mango_sylius_admin_contact_show:
  path: contact/show/{id}
  defaults:
    _controller: MangoSylius\SyliusContactFormPlugin\Controller\ContactFormAdminController:showMessageAction

mango_sylius_admin_contact_message:
  resource: |
    alias: mango_contact_form_plugin.message
    section: admin
    templates: SyliusAdminBundle:Crud
    except: ['show']
    redirect: update
    grid: mango_sylius_admin_contact_message
    vars:
        all:
            subheader: mango_contact_form_plugin.ui.subtitle
            header: mango_contact_form_plugin.ui.title
        index:
            icon: 'comments'
  type: sylius.resource
