sylius_resource:
  resources:
    mango_contact_form_plugin.message:
      classes:
        model: MangoSylius\SyliusContactFormPlugin\Entity\ContactFormMessage
        form: MangoSylius\SyliusContactFormPlugin\Form\Type\ContactFormType
        repository: MangoSylius\SyliusContactFormPlugin\Repository\ContactFormMessageRepository

    mango_contact_form_plugin.answer:
      classes:
        model: MangoSylius\SyliusContactFormPlugin\Entity\ContactFormMessageAnswer
        form: MangoSylius\SyliusContactFormPlugin\Form\Type\ContactFormMessageAnswer
        repository: MangoSylius\SyliusContactFormPlugin\Repository\ContactFormMessageAnswerRepository
