imports:
  - { resource: '@ThreeBRSSyliusContactFormPlugin/Resources/config/packages/resources.yml' }
  - { resource: '@ThreeBRSSyliusContactFormPlugin/Resources/config/packages/emails.yml' }
  - { resource: '@ThreeBRSSyliusContactFormPlugin/Resources/config/packages/grid.yml' }
  - { resource: '@ThreeBRSSyliusContactFormPlugin/Resources/config/packages/three_brs_sylius_contact_form.yml' }
