services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  MangoSylius\SyliusContactFormPlugin\Model\ContactFormSettingsProvider: ~

  MangoSylius\SyliusContactFormPlugin\Form\Type\ContactFormMessageType:
    tags:
      - name: form.type
    arguments:
      $contactFormSettings: '@MangoSylius\SyliusContactFormPlugin\Model\ContactFormSettingsProvider'

  MangoSylius\SyliusContactFormPlugin\Form\Type\ContactFormMessageAnswerType:
    tags:
      - name: form.type

  MangoSylius\SyliusContactFormPlugin\Menu\AdminContactMenuBuilder:
    tags:
      - name: kernel.event_listener
        event: sylius.menu.admin.main
        method: buildMenu

  MangoSylius\SyliusContactFormPlugin\Menu\AccountContactMenuBuilder:
    tags:
      - name: kernel.event_listener
        event: sylius.menu.shop.account
        method: buildMenu

  MangoSylius\SyliusContactFormPlugin\Controller\ContactFormAccountController:
    decorates: sylius.controller.shop.contact
    tags:
      - name: controller.service_arguments
    arguments:
      $translator: '@translator'
      $templatingEngine: '@templating'
      $entityManager: '@doctrine.orm.entity_manager'
      $router: '@router'
      $flashBag: '@session.flash_bag'
      $builder: '@form.factory'
      $channelContext: '@sylius.context.channel'
      $contactFormMessageRepository: '@mango_contact_form_plugin.repository.message'
      $contactFormMessageAnswerRepository: '@mango_contact_form_plugin.repository.answer'
      $tokenStorage: '@security.token_storage'

  MangoSylius\SyliusContactFormPlugin\Controller\ContactFormAdminController:
    decorates: sylius.controller.shop.contact
    tags:
      - name: controller.service_arguments
    arguments:
      $translator: '@translator'
      $templatingEngine: '@templating'
      $entityManager: '@doctrine.orm.entity_manager'
      $mailer: '@sylius.email_sender'
      $router: '@router'
      $flashBag: '@session.flash_bag'
      $builder: '@form.factory'
      $contactFormMessageRepository: '@mango_contact_form_plugin.repository.message'
      $contactFormMessageAnswerRepository: '@mango_contact_form_plugin.repository.answer'
      $tokenStorage: '@security.token_storage'

  MangoSylius\SyliusContactFormPlugin\Controller\ContactFormController:
    decorates: sylius.controller.shop.contact
    tags:
      - name: controller.service_arguments
    arguments:
      $contactFormSettings: '@MangoSylius\SyliusContactFormPlugin\Model\ContactFormSettingsProvider'
      $translator: '@translator'
      $templatingEngine: '@templating'
      $entityManager: '@doctrine.orm.entity_manager'
      $mailer: '@sylius.email_sender'
      $router: '@router'
      $flashBag: '@session.flash_bag'
      $builder: '@form.factory'
      $channelContext: '@sylius.context.channel'
      $tokenStorage: '@security.token_storage'
      $recaptchaPublic: '%env(string:GOOGLE_RECAPTCHA_SITE_KEY)%'
      $recaptchaSecret: '%env(string:GOOGLE_RECAPTCHA_SECRET)%'
