sylius_resource:
  resources:
    threebrs_sylius_contact_form_plugin.message:
      classes:
        model: ThreeBRS\SyliusContactFormPlugin\Entity\ContactFormMessage
        form: ThreeBRS\SyliusContactFormPlugin\Form\Type\ContactFormType
        repository: ThreeBRS\SyliusContactFormPlugin\Repository\ContactFormMessageRepository

    threebrs_sylius_contact_form_plugin.answer:
      classes:
        model: ThreeBRS\SyliusContactFormPlugin\Entity\ContactFormMessageAnswer
        form: ThreeBRS\SyliusContactFormPlugin\Form\Type\ContactFormMessageAnswer
        repository: ThreeBRS\SyliusContactFormPlugin\Repository\ContactFormMessageAnswerRepository
